#服务端口
server:
  port: 8000
#服务别名，注册到注册中心的服务别名
spring:
  application:
    name: yinzhh-server

eureka:
  instance:
    # 注册中心IP地址
    hostname: localhost
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://${eureka.instance.hostname}:8100/eureka/,http://${eureka.instance.hostname}:8200/eureka/
    # 需要将服务注册到eureka注册中心
    register-with-eureka: true
    # 由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
    fetch-registry: true
  server:
    # 默认为true，开启自我保护（false关闭自我保护）
    enable-self-preservation: false
    # 默认为0，续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
    eviction-interval-timer-in-ms: 5000
